# External dependencies for building iOS apps
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# Rules for building Apple apps
git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.19.0",  # Latest version, check for updates
)

git_repository(
    name = "build_bazel_rules_swift",
    remote = "https://github.com/bazelbuild/rules_swift.git",
    tag = "0.13.0",
)

git_repository(
    name = "build_bazel_apple_support",
    remote = "https://github.com/bazelbuild/apple_support.git",
    tag = "0.7.2",
)

git_repository(
    name = "bazel_skylib",
    remote = "https://github.com/bazelbuild/bazel-skylib.git",
    tag = "0.9.0",
)

# Optional: Custom Xcode version for building
load("@bazel_tools//tools/osx:xcode_config.bzl", "xcode_config")

xcode_config(
    name = "xcode",
    version = "12.4",  # Replace with the version of Xcode you are using
)

# Optional: Adding custom signing configuration for real device deployment
git_repository(
    name = "ios_signing_configs",
    remote = "https://github.com/your-org/ios-signing-configs.git",
    tag = "v1.0",
)